### ISSUE TITLE
我想知道有没有那种可以直接把 .md文档放入就可以做到一样的效果的方法!

### ISSUE THREAD

**Issue by sanbei101** [zhangyu1818/blog#131]

**Comment by zhangyu1818** [comment]
目前不支持哦，在最初设计是使用GitHub Discussions，如果要使用本地md文件主要难点是数据结构完全不同，改动会很多。

同时想要达到对应效果，markdown文件的改动也会比较大，需要再增加YAML配置以匹配数据结构，举例来说：

```markdown
---
title: 文章标题
number: 0 // 对应gitalk或giscus的评论
labels: 
  - JavaScript // 匹配Tag，但是会丢失颜色
  - React
createAt: 创建时间
updateAt: 更新时间
// 需要的属性都要增加...
---

markdown内容

```

**Comment by sanbei101** [comment]
> 目前不支持哦，在最初设计是使用GitHub Discussions，如果要使用本地md文件主要难点是数据结构完全不同，改动会很多。
> 
> 同时想要达到对应效果，markdown文件的改动也会比较大，需要再增加YAML配置以匹配数据结构，举例来说：
> 
> ```
> ---
> title: 文章标题
> number: 0 // 对应gitalk或giscus的评论
> labels: 
>   - JavaScript // 匹配Tag，但是会丢失颜色
>   - React
> createAt: 创建时间
> updateAt: 更新时间
> // 需要的属性都要增加...
> ---
> 
> markdown内容
> ```

好的,不过还是感谢大佬贡献了这么好看的主题!
