### ISSUE TITLE
把Github当作数据库，搭建博客

### ISSUE THREAD

**Issue by zhangyu1818** [zhangyu1818/blog#54]
网上有很多种搭建博客的方法，有前后台一把梭的，有静态网页的，也有大佬喜欢直接在Github的Issues上写文章。

今天给大家分享一种很方便的方法来搭建博客，无需服务器，前端可以是任意的技术栈。

可以实现的功能：

1. 前端页面自定义
2. 带评论系统
3. 文章可以带标签分类
4. 数据、图片保存在Github，长期储存
5. CDN加速
6. 自定义域名

当然，这种方式还是需要自己动手，并不是现成的一套技术。

最后的效果可以看我的[博客](https://zhangyu1818.com/)和[Github仓库](https://github.com/zhangyu1818/blog/issues?q=is%3Aissue+is%3Aclosed)。

## 如何实现

其实原理说出来很简单，因为Github有提供API接口的，可以访问Issues，而我们只需要通过Issues的接口来请求文章数据，每一篇文章对应一个Issue，每一个Issue的评论功能对应该文章的评论系统。

图片可以存储在当前仓库的另一个分支，用免费的[jsdelivr](https://www.jsdelivr.com/)来作CDN。

Github Page和一些`Serverless`提供商如[vercel](https://vercel.com/)都可以修改自定义域名。

## 创建仓库和Token

需要在Github上新建一个仓库，然后申请一个Github Token，申请方式见[官方文档](https://docs.github.com/cn/github/authenticating-to-github/creating-a-personal-access-token)。

这个Token需要保存好，不能传到仓库的，可以用`.env.local`这种方式来储存和读取。

## 读取博文列表

博文列表也就是Github Issues，官方提供了2种方式来获取，分别是[REST API](https://docs.github.com/en/rest)和[GraphQL API](https://docs.github.com/en/graphql)，需要使用官方的请求库[core.js](https://github.com/octokit/core.js#readme)。我是使用的GraphQL API，因为它可以提前过滤不要的数据。

比如我想要请求的Issues列表是仓库`zhangyu1818/blog`，拥有者为`zhangyu1818`，仓库名为`blog`，它对应的GrpahQL请求如下：

```javascript
{
  repository(owner: "zhangyu1818", name: "blog") {
    issues(
      states: CLOSED
      first: 100
      orderBy: { field: CREATED_AT, direction: DESC }
      filterBy: { createdBy: "zhangyu1818" }
    ) {
      nodes {
        number
        title
        createdAt
        updatedAt
        labels(first: 5) {
          nodes {
            color
            name
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
      totalCount
    }
  }
}
```

这一串数据请求了由zhangyu1818创建前100个关闭的Issue，每一个Issue请求前5个label标签，每一个Issue包含number、title、craetedAt等数据。

对应的REST API请求的方式和示例见[文档](https://docs.github.com/en/rest/reference/issues#list-repository-issues)。

## 请求文章详情

每一个Issue都是一个数字，用数字请求指定的Issue可以得到里面的详情。

```javascript
query queryIssueByNumber($number: Int!) {
  repository(owner: "zhangyu1818", name: "blog") {
    issue(number: $number) {
      number
      title
      url
      createdAt
      bodyHTML
      labels(first:5) {
        nodes{
          color
          name
        }
      }
    }
  }
}
```

Github API不仅可以请求Markdown的内容，也可以直接请求由Github渲染好的的内容HTML，这样我们连本地的Markdown渲染都可以省去。

对应的REST API请求的方式和示例见[文档](https://docs.github.com/en/rest/reference/issues#get-an-issue)。

## 评论系统

评论系统是有很多现成的轮子，这里推荐使用[`gitalk`](https://github.com/gitalk/gitalk)，使用方式见[文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md)。

需要先在Github创建一个[应用](https://github.com/settings/applications/new)，我的应用信息如下。

![image-20210408191220681](https://cdn.jsdelivr.net/gh/zhangyu1818/blog@files/files/image-20210408191220681.png)

**使用方式**

```javascript
const gitalk = new Gitalk({
  clientID: "GITHUB_CLIENT_ID", // 你的应用id
  clientSecret: "GITHUB_CLIENT_SECRET", // 你的应用secret
  repo: "blog", // 你的仓库
  owner: "zhangyu1818", // 你的github名字
  admin: ["zhangyu1818"], // 你的github名字
  number: 1, // 需要issueNumber相同
})

gitalk.render('gitalk-container') // 渲染的元素
```

## 图片储存在Github

这个也是现有工具就能实现的功能，图形化工具[PicGO](https://picgo.github.io/PicGo-Doc/)，它也有命令行工具[PicGo-Core](https://picgo.github.io/PicGo-Core-Doc/)，它同样需要使用Github Token，可以是之前申请的Token，也可以重新申请一个。

具体配置可以看[参考教程](https://juejin.cn/post/6844904137407086600)。

我配置的是将图片存在仓库的另一个分支。

![image-20210408192506499](https://cdn.jsdelivr.net/gh/zhangyu1818/blog@files/files/image-20210408192506499.png)

这样配置的话如果需要使用`jsdelivr`作CDN加速，配置的地址应该是

```
https://cdn.jsdelivr.net/gh/zhangyu1818/blog@files
```

## 页面的部署方式

部署方式推荐使用`vercel`,它可以很简单的配置在Github的主分支更新后自动的拉取和部署，同时支持很多种不同的前端技术栈，Vue和Angular都支持的，可以看[这里](https://vercel.com/new/templates)。

所以前端可以用任意的技术栈，我选择的是[`Next.js`](https://nextjs.org/docs/getting-started)，然后再通过`vercel`来部署。

`vercel`部署的还有一个好处是可以在页面上配置一些环境变量，比如我们的Github Token，聊天的Client ID，同时也可以修改自定义的域名。

![image-20210408193426232](https://cdn.jsdelivr.net/gh/zhangyu1818/blog@files/files/image-20210408193426232.png)

配置好后代码里可以直接这样写。

```javascript
const gitalk = new Gitalk({
  clientID: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,
  clientSecret: process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET,
  // ...
})
```

## sitemap如何实现

如果是静态页面，可以需要在`build`之前先请求列表，再写一个`sitemap.xml`到本地，如果是服务端渲染，可以直接写一个API接口。

## 总结

这个博客我也用了挺久了，总的来说非常方便，是我折腾博客多年来说最好的一个方式，不需要本地储存数据，也不需要后台，也不需要买服务器来部署，Github上和网页就是一个镜像，需要改文章内容或者是标签，只需要在Github上改一下就行了。

唯一的缺点就是需要自己折腾折腾，对于爱动手的小伙伴来说，我觉得这种方式的自由度是很高的了。

**Comment by chenkun76** [comment]
评论一下

**Comment by Noric1417** [comment]
w

**Comment by Noric1417** [comment]
請問下 弄好token後 如何讓網頁能夠吃到裡面的資料 並顯示出來 我們想做一個能夠驗證帳號密碼的網頁 並在登入後 顯示資料庫中的圖片

**Comment by zhangyu1818** [comment]
@Noric1417 不太明白你的需求，如果说是想获取GitHub的数据，用官方的[core.js](https://github.com/octokit/core.js#readme)就可以了，如果是图片存在GitHub仓库的，直接读取对应的分支路径就行了，但是如果仓库是私有的，里面的图片应该是读取不到的

**Comment by Noric1417** [comment]
我的意思是 我們想要設置一個網站，讓網站能夠點選註冊，並將帳號密碼儲存進GITHUB ，並在之後使這個網站在登入時能夠驗證這個帳號密碼是否註冊過，這是做的到的嬤

**Comment by zhangyu1818** [comment]
理论上能做到，因为有api可以读取和修改仓库文件，不过这样在网页上只能全量读取明文的文件内容，不太适用。

**Comment by Normal-pcer** [comment]
我觉得可以直接在github的某个issues中直接保存json格式的数据，再通过javascript读取。
账号明文保存，密码用安全的哈希（SHA256这种），在对安全性要求小的情况下应该没啥问题。

类似于：
```json
{
"userdata": {
"ZhangSan": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
"LiSi": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
"WangEr_ma_zi": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
}
}
```

```
Github总是被用于奇怪的用途
                   ——鲁逊
```

**Comment by HKEMS-STMO-Webmasters** [comment]
> 請問下 弄好token後 如何讓網頁能夠吃到裡面的資料 並顯示出來 我們想做一個能夠驗證帳號密碼的網頁 並在登入後 顯示資料庫中的圖片

你好，这里的数据是存储在github的issue中的，也就是如果您想用这种方法制作登录系统，那么所有的账号和密码都会存储在issue中，我想这和明文存储没什么区别，所以我建议您更换一种思路。
